import nbformat as nbf

def create_notebook(filename):
    nb = nbf.v4.new_notebook()
    cells = []
    
    cells.append(nbf.v4.new_markdown_cell("# Task 3: Forecast Future Market Trends\\n\\nWe forecast TSLA's future stock prices for the next 6-12 months (e.g. up to mid 2027) using the trained ARIMA model, visualize confidence intervals, and perform trend analysis."))
    
    cells.append(nbf.v4.new_code_cell("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pmdarima as pm
import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8')"""))

    cells.append(nbf.v4.new_markdown_cell("## 1 & 2. Generate and Visualize Future Forecasts with Confidence Intervals"))
    cells.append(nbf.v4.new_code_cell("""# Load data and fit ARIMA on the ENTIRE dataset (to forecast into the future)
df = pd.read_csv('../data/processed/historical_data.csv', header=[0,1], index_col=0, parse_dates=True)
tsla_close = df['Adj Close']['TSLA'].dropna()

print("Fitting ARIMA model on all available data...")
arima_model = pm.auto_arima(tsla_close, seasonal=False, stepwise=True, trace=False)

# Forecast for 6 months (approx 126 trading days)
forecast_periods = 126
forecast, conf_int = arima_model.predict(n_periods=forecast_periods, return_conf_int=True)

# Create future dates index
future_dates = pd.bdate_range(start=tsla_close.index[-1] + pd.Timedelta(days=1), periods=forecast_periods)
forecast.index = future_dates

# Plot
plt.figure(figsize=(14, 7))
plt.plot(tsla_close['2024':], label='Historical Data')
plt.plot(forecast.index, forecast, color='green', label='Future Forecast')
plt.fill_between(forecast.index, conf_int[:, 0], conf_int[:, 1], color='green', alpha=0.2, label='Confidence Interval')
plt.title('TSLA 6-Month Price Forecast')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.show()"""))

    cells.append(nbf.v4.new_markdown_cell("## 3 & 4. Trend Analysis and Market Opportunities/Risks\\n\\n**Trend Analysis:**\\nThe forecast generated by the ARIMA model often reflects a continuation of the most recent trend or mean-reversion. In financial time series, long-term forecasts via ARIMA tend to flatten out. The confidence intervals widen significantly as we look further into the 6-month horizon, representing the high uncertainty in predicting exact stock prices long-term.\\n\\n**Opportunities and Risks:**\\n- **Opportunities:** If the forecast is upward, it may suggest a momentum play.\\n- **Risks:** The extremely wide confidence intervals highlight massive downside risk. The Efficient Market Hypothesis tells us that standalone price prediction is unreliable.\\n- **Reliability:** Over a 6-12 month horizon, model-based price forecasts should be treated as a measure of expected volatility rather than directional certainty."))

    nb['cells'] = cells
    with open(filename, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)

if __name__ == '__main__':
    create_notebook('../notebooks/Task_3_Forecast.ipynb')
    print("Notebook generated at ../notebooks/Task_3_Forecast.ipynb")
